#Specify main directory to load config file
MAIN_DIR = ..
CONFIG_FILE = $(MAIN_DIR)/config.mk
include ${CONFIG_FILE}

clean:
	@echo "        Cleaning directory: python/ ... "
	rm -f $(MAKE_CLEAN_ARGUMENTS)
